//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin_for_game
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int idType { get; set; }
        public int idRarity { get; set; }
        public Nullable<int> idSet { get; set; }
        public Nullable<int> style { get; set; }
        public int price { get; set; }
        public string picture { get; set; }
        public System.DateTime dateRelease { get; set; }
    
        public virtual ItemSets ItemSets { get; set; }
        public virtual RarityItem RarityItem { get; set; }
        public virtual TypeItem TypeItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
