//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin_for_game
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedItemSets
    {
        public int PlayerId { get; set; }
        public int HeadId { get; set; }
        public int BodyId { get; set; }
        public int LegId { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Items Items1 { get; set; }
        public virtual Items Items2 { get; set; }
        public virtual Players Players { get; set; }
    }
}
